version: "3.7"

volumes:
  logs:
    driver: local

services:
  web:
    image: thebiggive/php:8.0
    ports:
      - 30040:80
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      - redis

  consumer:
    image: thebiggive/php:8.0
    entrypoint: docker-php-entrypoint
    command: composer run messenger:consume
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      - redis
      - smtp

  redis:
    image: redis:5.0

  smtp:
    image: namshi/smtp
