version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.0.0
  aws-ecr: circleci/aws-ecr@9.3.1
  aws-ecs: circleci/aws-ecs@4.1.0
  jira: circleci/jira@2.1.0
  slack: circleci/slack@4.13.3

jobs:
  test: # Also lints first
    docker:
      - image: thebiggive/php:8.3
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN

    steps:
      - checkout

      - restore_cache:
          keys:
            - composer-v3-{{ checksum "composer.lock" }}

      - run: composer install --no-interaction
      - run: cd docs && apt update && apt install -y npm && npm i swagger-ui-dist

      - save_cache:
          paths:
            - vendor
            - docs/node-modules
          key: composer-v3-{{ checksum "composer.lock" }}

      - run: composer run lint:check

      - run:
          name: Generate OpenAPI spec
          command: composer run docs

      - run: composer run sa:check

      - run: composer run test

      - store_artifacts:
          path: docs

workflows:
  build:
    jobs:
      - test:
          context:
            - docker-hub-creds
            - jira
            - slack
          post-steps:
            - jira/notify:
                pipeline_id: << pipeline.id >>
                pipeline_number: << pipeline.number >>
                job_type: build
                environment_type: development
            - slack/notify:
                event: fail
                template: basic_fail_1

  deploy-staging:
    jobs:
      - test:
          filters:
            branches:
              only:
                - develop
          context:
            - docker-hub-creds
      - aws-ecr/build_and_push_image:
          context:
            - ecs-deploys
          requires:
            - test
          repo: '${AWS_ECR_REPO_NAME}'
          tag: 'staging,staging-${CIRCLE_SHA1}'
          auth:
            - aws-cli/setup:
                aws_access_key_id: AWS_ACCESS_KEY_ID
                aws_secret_access_key: AWS_SECRET_ACCESS_KEY
      - aws-ecs/deploy_service_update:
          context:
            - ecs-deploys
            - slack
          requires:
            - aws-ecr/build_and_push_image
          family: 'tbg-staging-${AWS_REGION}-${AWS_ECS_SERVICE_SUFFIX_TASKS}'
          cluster: 'tbg-staging-${AWS_REGION}'
          container_image_name_updates: 'container=mailer_tasks,tag=staging-${CIRCLE_SHA1}'
          auth:
            - aws-cli/setup:
                aws_access_key_id: AWS_ACCESS_KEY_ID
                aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          post-steps:
            - slack/notify:
                event: fail
                template: basic_fail_1
            - slack/notify:
                custom: |
                  {
                    "blocks": [
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "mrkdwn",
                            "text": "*Staging: Mailer tasks deployed!*"
                          }
                        ]
                      }
                    ]
                  }
      - aws-ecs/deploy_service_update:
          context:
            - ecs-deploys
            - jira
            - slack
          requires:
            - aws-ecr/build_and_push_image
          family: 'tbg-staging-${AWS_REGION}-${AWS_ECS_SERVICE_SUFFIX_WEB}'
          cluster: 'tbg-staging-${AWS_REGION}'
          container_image_name_updates: 'container=mailer_web,tag=staging-${CIRCLE_SHA1}'
          auth:
            - aws-cli/setup:
                aws_access_key_id: AWS_ACCESS_KEY_ID
                aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          post-steps:
            - slack/notify:
                event: fail
                template: basic_fail_1
            - jira/notify:
                pipeline_id: << pipeline.id >>
                pipeline_number: << pipeline.number >>
                job_type: deployment
                environment: Staging
                environment_type: staging
            - slack/notify:
                custom: |
                  {
                    "blocks": [
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "mrkdwn",
                            "text": "*Staging: Mailer web deployed!* All visitors should see the updated app version within 30 minutes."
                          }
                        ]
                      }
                    ]
                  }
  deploy-regression:
    jobs:
      - test:
          filters:
            branches:
              only:
                - develop
          context:
            - docker-hub-creds
      - aws-ecr/build_and_push_image:
          context:
            - ecs-deploys
          requires:
            - test
          repo: '${AWS_ECR_REPO_NAME}'
          tag: 'regression,regression-${CIRCLE_SHA1}'
          auth:
            - aws-cli/setup:
                aws_access_key_id: AWS_ACCESS_KEY_ID
                aws_secret_access_key: AWS_SECRET_ACCESS_KEY
      - aws-ecs/deploy_service_update:
          context:
            - ecs-deploys
            - slack
          requires:
            - aws-ecr/build_and_push_image
          family: 'tbg-regression-${AWS_REGION}-${AWS_ECS_SERVICE_SUFFIX_TASKS}'
          cluster: 'tbg-regression-${AWS_REGION}'
          container_image_name_updates: 'container=mailer_tasks,tag=regression-${CIRCLE_SHA1}'
          auth:
            - aws-cli/setup:
                aws_access_key_id: AWS_ACCESS_KEY_ID
                aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          post-steps:
            - slack/notify:
                event: fail
                template: basic_fail_1
            - slack/notify:
                custom: |
                  {
                    "blocks": [
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "mrkdwn",
                            "text": "*Regression: Mailer tasks deployed!*"
                          }
                        ]
                      }
                    ]
                  }
      - aws-ecs/deploy_service_update:
          context:
            - ecs-deploys
            - jira
            - slack
          requires:
            - aws-ecr/build_and_push_image
          family: 'tbg-regression-${AWS_REGION}-${AWS_ECS_SERVICE_SUFFIX_WEB}'
          cluster: 'tbg-regression-${AWS_REGION}'
          container_image_name_updates: 'container=mailer_web,tag=regression-${CIRCLE_SHA1}'
          auth:
            - aws-cli/setup:
                aws_access_key_id: AWS_ACCESS_KEY_ID
                aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          post-steps:
            - slack/notify:
                event: fail
                template: basic_fail_1
            - jira/notify:
                pipeline_id: << pipeline.id >>
                pipeline_number: << pipeline.number >>
                job_type: deployment
                environment: Regression
                environment_type: staging
            - slack/notify:
                custom: |
                  {
                    "blocks": [
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "mrkdwn",
                            "text": "*Regression: Mailer web deployed!* All visitors should see the updated app version within 30 minutes."
                          }
                        ]
                      }
                    ]
                  }
  deploy-production:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
          context:
            - docker-hub-creds
      - aws-ecr/build_and_push_image:
          context:
            - ecs-deploys
          requires:
            - test
          repo: '${AWS_ECR_REPO_NAME}'
          tag: 'production,production-${CIRCLE_SHA1}'
          auth:
            - aws-cli/setup:
                aws_access_key_id: AWS_ACCESS_KEY_ID
                aws_secret_access_key: AWS_SECRET_ACCESS_KEY
      - aws-ecs/deploy_service_update:
          context:
            - ecs-deploys
            - slack
          requires:
            - aws-ecr/build_and_push_image
          family: 'tbg-production-${AWS_REGION}-${AWS_ECS_SERVICE_SUFFIX_TASKS}'
          cluster: 'tbg-production-${AWS_REGION}'
          container_image_name_updates: 'container=mailer_tasks,tag=production-${CIRCLE_SHA1}'
          auth:
            - aws-cli/setup:
                aws_access_key_id: AWS_ACCESS_KEY_ID
                aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          post-steps:
            - slack/notify:
                event: fail
                template: basic_fail_1
            - slack/notify:
                custom: |
                  {
                    "blocks": [
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "mrkdwn",
                            "text": "*Production: Mailer tasks deployed!*"
                          }
                        ]
                      }
                    ]
                  }
      - aws-ecs/deploy_service_update:
          context:
            - ecs-deploys
            - jira
            - slack
          requires:
            - aws-ecr/build_and_push_image
          family: 'tbg-production-${AWS_REGION}-${AWS_ECS_SERVICE_SUFFIX_WEB}'
          cluster: 'tbg-production-${AWS_REGION}'
          container_image_name_updates: 'container=mailer_web,tag=production-${CIRCLE_SHA1}'
          auth:
            - aws-cli/setup:
                aws_access_key_id: AWS_ACCESS_KEY_ID
                aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          post-steps:
            - slack/notify:
                event: fail
                template: basic_fail_1
            - jira/notify:
                pipeline_id: << pipeline.id >>
                pipeline_number: << pipeline.number >>
                job_type: deployment
                environment: Production
                environment_type: production
            - slack/notify:
                custom: |
                  {
                    "blocks": [
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "mrkdwn",
                            "text": "*Production: Mailer web deployed!* All visitors should see the updated app version within 30 minutes."
                          }
                        ]
                      }
                    ]
                  }
