version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@2.1.0
  jira: circleci/jira@1.3.1
  slack: circleci/slack@4.3.3

jobs:
  test: # Also lints first
    docker:
      - image: circleci/php:8.0
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN

    steps:
      - checkout

      - run: sudo apt-get install -y libzip-dev zip
      - run: sudo docker-php-ext-install bcmath pdo_mysql zip
      - run: sudo pecl install redis && sudo docker-php-ext-enable redis

      - restore_cache:
          keys:
            - composer-v2-{{ checksum "composer.lock" }}

      - run: composer install --no-interaction

      - save_cache:
          paths:
            - vendor
          key: composer-v2-{{ checksum "composer.lock" }}

      - run: composer run lint:check

      - run: composer run docs # Ensure OpenAPI annotations remain valid

      - run: composer run test

workflows:
  build:
    jobs:
      - test:
          context:
            - docker-hub-creds
          post-steps:
            - jira/notify:
                job_type: build
                environment_type: development
            - slack/notify-on-failure: ~

  deploy-staging:
    jobs:
      - test:
          filters:
            branches:
              only:
                - develop
          context:
            - docker-hub-creds
      - aws-ecr/build-and-push-image:
          requires:
            - test
          repo: '${AWS_ECR_REPO_NAME}'
          region: AWS_REGION
          tag: 'staging,staging-${CIRCLE_SHA1}'
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          aws-region: '${AWS_REGION}'
          family: 'tbg-staging-${AWS_REGION}-${AWS_ECS_SERVICE_SUFFIX_TASKS}'
          cluster-name: 'tbg-staging-${AWS_REGION}'
          container-image-name-updates: 'container=mailer_tasks,tag=staging-${CIRCLE_SHA1}'
          post-steps:
            - slack/notify-on-failure: ~
            - slack/notify:
                color: '#009900'
                message: 'We use rolling blue/green deploys. All visitors to staging will see the updated app version within ~30 minutes.'
                title: 'Staging: Mailer tasks deployed!'
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          aws-region: '${AWS_REGION}'
          family: 'tbg-staging-${AWS_REGION}-${AWS_ECS_SERVICE_SUFFIX_WEB}'
          cluster-name: 'tbg-staging-${AWS_REGION}'
          container-image-name-updates: 'container=mailer_web,tag=staging-${CIRCLE_SHA1}'
          post-steps:
            - slack/notify-on-failure: ~
            - jira/notify:
                job_type: deployment
                environment_type: staging
            - slack/notify:
                color: '#009900'
                message: 'We use rolling blue/green deploys. All visitors to staging will see the updated app version within ~30 minutes.'
                title: 'Staging: Mailer web deployed!'

  deploy-regression:
    jobs:
      - test:
          filters:
            branches:
              only:
                - develop
          context:
            - docker-hub-creds
      - aws-ecr/build-and-push-image:
          requires:
            - test
          repo: '${AWS_ECR_REPO_NAME}'
          region: AWS_REGION
          tag: 'regression,regression-${CIRCLE_SHA1}'
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          aws-region: '${AWS_REGION}'
          family: 'tbg-regression-${AWS_REGION}-${AWS_ECS_SERVICE_SUFFIX_TASKS}'
          cluster-name: 'tbg-regression-${AWS_REGION}'
          container-image-name-updates: 'container=mailer_tasks,tag=regression-${CIRCLE_SHA1}'
          post-steps:
            - slack/notify-on-failure: ~
            - slack/notify:
                color: '#009900'
                message: 'We use rolling blue/green deploys. All visitors to regression will see the updated app version within ~30 minutes.'
                title: 'Regression: Mailer tasks deployed!'
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          aws-region: '${AWS_REGION}'
          family: 'tbg-regression-${AWS_REGION}-${AWS_ECS_SERVICE_SUFFIX_WEB}'
          cluster-name: 'tbg-regression-${AWS_REGION}'
          container-image-name-updates: 'container=mailer_web,tag=regression-${CIRCLE_SHA1}'
          post-steps:
            - slack/notify-on-failure: ~
            - jira/notify:
                job_type: deployment
                environment_type: staging
            - slack/notify:
                color: '#009900'
                message: 'We use rolling blue/green deploys. All visitors to regression will see the updated app version within ~30 minutes.'
                title: 'Regression: Mailer web deployed!'

  deploy-production:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
          context:
            - docker-hub-creds
      - aws-ecr/build-and-push-image:
          requires:
            - test
          repo: '${AWS_ECR_REPO_NAME}'
          region: AWS_REGION
          tag: 'production,production-${CIRCLE_SHA1}'
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          aws-region: '${AWS_REGION}'
          family: 'tbg-production-${AWS_REGION}-${AWS_ECS_SERVICE_SUFFIX_TASKS}'
          cluster-name: 'tbg-production-${AWS_REGION}'
          container-image-name-updates: 'container=mailer_tasks,tag=production-${CIRCLE_SHA1}'
          post-steps:
            - slack/notify-on-failure: ~
            - slack/notify:
                color: '#009900'
                message: 'We use rolling blue/green deploys. All visitors to production will see the updated app version within ~30 minutes.'
                title: 'Production: Mailer tasks deployed!'
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          aws-region: '${AWS_REGION}'
          family: 'tbg-production-${AWS_REGION}-${AWS_ECS_SERVICE_SUFFIX_WEB}'
          cluster-name: 'tbg-production-${AWS_REGION}'
          container-image-name-updates: 'container=mailer_web,tag=production-${CIRCLE_SHA1}'
          post-steps:
            - slack/notify-on-failure: ~
            - jira/notify:
                job_type: deployment
                environment_type: production
            - slack/notify:
                color: '#009900'
                message: 'We use rolling blue/green deploys. All visitors to production will see the updated app version within ~30 minutes.'
                title: 'Production: Mailer web deployed!'
